### ISSUE TITLE
安装命令不对啊

### ISSUE THREAD

**Issue by wmlc** [jyiL/crontab-extension#1]
composer require jyil/crontab

**Comment by jyiL** [comment]
报什么错

**Comment by wmlc** [comment]
> 报什么错

你文档里写的   
`composer require jyil/crontab-extension`  应该 `composer require jyil/crontab` 吧

**Comment by jyiL** [comment]
> > 报什么错
> 
> 你文档里写的
> `composer require jyil/crontab-extension` 应该`composer require jyil/crontab`吧

那个忘记改了,不好意思哈

**Comment by wmlc** [comment]
没事  扩展很好  不是在扩展中执行的命令日志我也往你这个扩展里扔    查看执行日志挺好用的
